//! Adapter that serves an existing tddy-rpc `ConnectionService` implementation
//! (e.g. [`crate::connection_service::ConnectionServiceImpl`]) over native tonic gRPC.
//!
//! The daemon's handler is written against the tddy-rpc flavor of the service trait
//! (`tddy_service::proto::connection::ConnectionService`, using `tddy_rpc::{Request, Response,
//! Status, Streaming}`). This adapter implements the tonic flavor
//! (`tddy_service::tonic_connection::connection_service_server::ConnectionService`, using
//! `tonic::{Request, Response, Status, Streaming}`) by delegating each method to the inner
//! handler and converting the wrapper types at the boundary.
//!
//! Both flavors reference the identical canonical prost message types (via `extern_path` in
//! `tddy-service/build.rs`), so no message re-encode/decode is needed — only the transport
//! wrappers and the error `Status` are converted. The tddy-rpc `tonic` feature provides `From`
//! impls for these conversions, but it pins tonic 0.11 while the generated tonic service targets
//! tonic 0.12; the conversions are therefore written explicitly against the 0.12 types, in
//! [`tddy_service::tonic_status`], where every adapter — hand-written or `tddy-codegen`-emitted —
//! can reach them.
//!
//! Each method is spelled out as a literal `async fn` (rather than generated by a declarative
//! macro) because `#[tonic::async_trait]` rewrites method signatures and cannot see through a
//! macro invocation.
//!
//! This is plumbing only: constructing the adapter does not start a server. Wiring a
//! `tonic::transport::Server` around `ConnectionServiceServer::new(adapter)` is a later step.

use std::pin::Pin;
use std::sync::Arc;

use futures_util::{Stream, StreamExt};
use tddy_github::{GitHubUser, SessionTokenSigner};
use tonic::transport::server::UdsConnectInfo;

use crate::config::DaemonConfig;
use tddy_service::proto::connection::ConnectionService as RpcConnectionService;
use tddy_service::proto::connection::{
    AddProjectToHostRequest, AddProjectToHostResponse, ConnectSessionRequest,
    ConnectSessionResponse, CreateProjectRequest, CreateProjectResponse, DeleteSessionRequest,
    DeleteSessionResponse, GetDemoVmStatusRequest, GetDemoVmStatusResponse,
    GetWorktreeSnapshotRequest, GetWorktreeSnapshotResponse, ListProjectBranchesRequest,
    ListProjectBranchesResponse, ListProjectsRequest, ListProjectsResponse, ListSessionsRequest,
    ListSessionsResponse, MintLocalTokenRequest, MintLocalTokenResponse, ResumeSessionRequest,
    ResumeSessionResponse, SetProjectDefaultBranchRequest, SetProjectDefaultBranchResponse,
    SignalSessionRequest, SignalSessionResponse, StartDemoVmRequest, StartDemoVmResponse,
    StartSessionEvent, StartSessionRequest, StartSessionResponse, StopDemoVmRequest,
    StopDemoVmResponse,
};
use tddy_service::tonic_connection::connection_service_server::ConnectionService as TonicConnectionService;

/// The `Status` conversions both directions of an adapter need live in `tddy-service`, next to the
/// generated service traits, so `tddy-codegen`-emitted adapters (which land in another crate's
/// `OUT_DIR`) reach the same pair this adapter uses. Re-exported here because callers outside this
/// module already refer to them through this path.
pub use tddy_service::{to_rpc_status, to_tonic_status};

/// Maps a peer uid (from SO_PEERCRED) to its OS username. Injected so the local peer-trust path is
/// host-independent and unit-testable; production wires the passwd lookup
/// (`crate::user_sessions_path::username_for_uid`).
pub type UidToUsername = Arc<dyn Fn(u32) -> Option<String> + Send + Sync>;

/// Wraps a tddy-rpc `ConnectionService` implementation so it can be served over tonic gRPC.
///
/// Construct with [`ConnectionServiceTonicAdapter::new`] and hand to
/// `tddy_service::tonic_connection::connection_service_server::ConnectionServiceServer::new`.
///
/// Every method delegates to the inner tddy-rpc handler except `MintLocalToken`, which is handled
/// here at the tonic layer: it reads the caller's peer uid from the Unix-domain-socket connect-info
/// (`UdsConnectInfo`, populated by tonic on the local socket transport), resolves it against the
/// daemon `users[]` mapping, and mints an access token with the shared `SessionTokenSigner`.
pub struct ConnectionServiceTonicAdapter<T> {
    inner: Arc<T>,
    config: Arc<DaemonConfig>,
    signer: Option<SessionTokenSigner>,
    uid_to_username: UidToUsername,
}

impl<T> ConnectionServiceTonicAdapter<T> {
    pub fn new(
        inner: Arc<T>,
        config: Arc<DaemonConfig>,
        signer: Option<SessionTokenSigner>,
        uid_to_username: UidToUsername,
    ) -> Self {
        Self {
            inner,
            config,
            signer,
            uid_to_username,
        }
    }
}

#[tonic::async_trait]
impl<T> TonicConnectionService for ConnectionServiceTonicAdapter<T>
where
    T: RpcConnectionService,
{
    // `result_large_err`: the `Err` is `tonic::Status`, mandated by the generated tonic trait — it
    // cannot be boxed, so the lint's suggested fix does not apply. Every other `#[allow]` of this
    // lint in this file is for the same reason.
    #[allow(clippy::result_large_err)]
    async fn list_sessions(
        &self,
        request: tonic::Request<ListSessionsRequest>,
    ) -> Result<tonic::Response<ListSessionsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_sessions(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_projects(
        &self,
        request: tonic::Request<ListProjectsRequest>,
    ) -> Result<tonic::Response<ListProjectsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_projects(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn create_project(
        &self,
        request: tonic::Request<CreateProjectRequest>,
    ) -> Result<tonic::Response<CreateProjectResponse>, tonic::Status> {
        let resp = RpcConnectionService::create_project(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn add_project_to_host(
        &self,
        request: tonic::Request<AddProjectToHostRequest>,
    ) -> Result<tonic::Response<AddProjectToHostResponse>, tonic::Status> {
        let resp = RpcConnectionService::add_project_to_host(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn start_session(
        &self,
        request: tonic::Request<StartSessionRequest>,
    ) -> Result<tonic::Response<StartSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::start_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn connect_session(
        &self,
        request: tonic::Request<ConnectSessionRequest>,
    ) -> Result<tonic::Response<ConnectSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::connect_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn resume_session(
        &self,
        request: tonic::Request<ResumeSessionRequest>,
    ) -> Result<tonic::Response<ResumeSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::resume_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn signal_session(
        &self,
        request: tonic::Request<SignalSessionRequest>,
    ) -> Result<tonic::Response<SignalSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::signal_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn delete_session(
        &self,
        request: tonic::Request<DeleteSessionRequest>,
    ) -> Result<tonic::Response<DeleteSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::delete_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_project_branches(
        &self,
        request: tonic::Request<ListProjectBranchesRequest>,
    ) -> Result<tonic::Response<ListProjectBranchesResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_project_branches(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn set_project_default_branch(
        &self,
        request: tonic::Request<SetProjectDefaultBranchRequest>,
    ) -> Result<tonic::Response<SetProjectDefaultBranchResponse>, tonic::Status> {
        let resp = RpcConnectionService::set_project_default_branch(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    // `result_large_err`: see `list_sessions`.
    #[allow(clippy::result_large_err)]
    async fn start_demo_vm(
        &self,
        request: tonic::Request<StartDemoVmRequest>,
    ) -> Result<tonic::Response<StartDemoVmResponse>, tonic::Status> {
        let resp = RpcConnectionService::start_demo_vm(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn stop_demo_vm(
        &self,
        request: tonic::Request<StopDemoVmRequest>,
    ) -> Result<tonic::Response<StopDemoVmResponse>, tonic::Status> {
        let resp = RpcConnectionService::stop_demo_vm(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn get_demo_vm_status(
        &self,
        request: tonic::Request<GetDemoVmStatusRequest>,
    ) -> Result<tonic::Response<GetDemoVmStatusResponse>, tonic::Status> {
        let resp = RpcConnectionService::get_demo_vm_status(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn get_worktree_snapshot(
        &self,
        request: tonic::Request<GetWorktreeSnapshotRequest>,
    ) -> Result<tonic::Response<GetWorktreeSnapshotResponse>, tonic::Status> {
        let resp = RpcConnectionService::get_worktree_snapshot(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    /// Peer-trust minting, handled at the tonic layer rather than delegated: the peer credential is
    /// only present on the local Unix-domain-socket transport. Deny when there is no peer-cred
    /// (any non-UDS transport), when the peer uid maps to no configured user, or when no signer is
    /// configured.
    async fn mint_local_token(
        &self,
        request: tonic::Request<MintLocalTokenRequest>,
    ) -> Result<tonic::Response<MintLocalTokenResponse>, tonic::Status> {
        let uid = request
            .extensions()
            .get::<UdsConnectInfo>()
            .and_then(|info| info.peer_cred.as_ref())
            .map(|cred| cred.uid())
            .ok_or_else(|| {
                tonic::Status::permission_denied(
                    "local token minting requires a Unix-domain-socket peer credential",
                )
            })?;

        let login = self
            .config
            .local_token_login_for_uid(uid, self.uid_to_username.as_ref())
            .ok_or_else(|| {
                tonic::Status::permission_denied(format!(
                    "peer uid {uid} is not mapped to a configured user"
                ))
            })?;

        let signer = self.signer.as_ref().ok_or_else(|| {
            tonic::Status::failed_precondition("local token minting requires a configured signer")
        })?;

        // The mapping resolves only a GitHub login; the rest of the identity is not needed to
        // authenticate subsequent RPCs (the resolver keys on `login`).
        let user = GitHubUser {
            id: 0,
            login: login.clone(),
            avatar_url: String::new(),
            name: login,
        };
        let session_token = signer.mint_access(&user);
        Ok(tonic::Response::new(MintLocalTokenResponse {
            session_token,
        }))
    }

    /// Server streaming: attachment-materialization progress, then one terminal result.
    type StreamStartSessionStream =
        Pin<Box<dyn Stream<Item = Result<StartSessionEvent, tonic::Status>> + Send>>;

    #[allow(clippy::result_large_err)]
    async fn stream_start_session(
        &self,
        request: tonic::Request<StartSessionRequest>,
    ) -> Result<tonic::Response<Self::StreamStartSessionStream>, tonic::Status> {
        let resp = RpcConnectionService::stream_start_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        let outbound = resp.into_inner().map(|item| item.map_err(to_tonic_status));
        Ok(tonic::Response::new(Box::pin(outbound)))
    }
}
