//! Adapter that serves an existing tddy-rpc `ConnectionService` implementation
//! (e.g. [`crate::connection_service::ConnectionServiceImpl`]) over native tonic gRPC.
//!
//! The daemon's handler is written against the tddy-rpc flavor of the service trait
//! (`tddy_service::proto::connection::ConnectionService`, using `tddy_rpc::{Request, Response,
//! Status, Streaming}`). This adapter implements the tonic flavor
//! (`tddy_service::tonic_connection::connection_service_server::ConnectionService`, using
//! `tonic::{Request, Response, Status, Streaming}`) by delegating each method to the inner
//! handler and converting the wrapper types at the boundary.
//!
//! Both flavors reference the identical canonical prost message types (via `extern_path` in
//! `tddy-service/build.rs`), so no message re-encode/decode is needed — only the transport
//! wrappers and the error `Status` are converted. The tddy-rpc `tonic` feature provides `From`
//! impls for these conversions, but it pins tonic 0.11 while the generated tonic service targets
//! tonic 0.12; the conversions here are therefore written explicitly against the 0.12 types.
//!
//! Each method is spelled out as a literal `async fn` (rather than generated by a declarative
//! macro) because `#[tonic::async_trait]` rewrites method signatures and cannot see through a
//! macro invocation.
//!
//! This is plumbing only: constructing the adapter does not start a server. Wiring a
//! `tonic::transport::Server` around `ConnectionServiceServer::new(adapter)` is a later step.

use std::pin::Pin;
use std::sync::Arc;

use futures_util::{Stream, StreamExt};
use tddy_github::{GitHubUser, SessionTokenSigner};
use tonic::transport::server::UdsConnectInfo;

use crate::config::DaemonConfig;
use tddy_service::proto::connection::ConnectionService as RpcConnectionService;
use tddy_service::proto::connection::{
    AddPlannedPrRequest, AddPlannedPrResponse, AddProjectToHostRequest, AddProjectToHostResponse,
    ClaimTerminalControlRequest, ClaimTerminalControlResponse, ConnectSessionRequest,
    ConnectSessionResponse, CreateProjectRequest, CreateProjectResponse, DeleteSessionRequest,
    DeleteSessionResponse, ExecuteToolRequest, ExecuteToolResponse, GetDemoVmStatusRequest,
    GetDemoVmStatusResponse, ListAgentModelsRequest, ListAgentModelsResponse, ListAgentsRequest,
    ListAgentsResponse, ListEligibleDaemonsRequest, ListEligibleDaemonsResponse,
    ListExecToolsRequest, ListExecToolsResponse, ListProjectBranchesRequest,
    ListProjectBranchesResponse, ListProjectsRequest, ListProjectsResponse,
    ListSessionToolCallsRequest, ListSessionToolCallsResponse, ListSessionWorkflowFilesRequest,
    ListSessionWorkflowFilesResponse, ListSessionsRequest, ListSessionsResponse,
    ListSubagentsRequest, ListSubagentsResponse, ListTerminalSessionsRequest,
    ListTerminalSessionsResponse, ListToolsRequest, ListToolsResponse,
    ListWorktreesForProjectRequest, ListWorktreesForProjectResponse, MintLocalTokenRequest,
    MintLocalTokenResponse, ReadSessionWorkflowFileRequest, ReadSessionWorkflowFileResponse,
    RemoveWorktreeRequest, RemoveWorktreeResponse, ReportSessionStatusRequest,
    ReportSessionStatusResponse, ResumeSessionRequest, ResumeSessionResponse,
    SendTerminalInputResponse, SessionTerminalInput, SessionTerminalOutput, SignalSessionRequest,
    SignalSessionResponse, StartDemoVmRequest, StartDemoVmResponse, StartSessionRequest,
    StartSessionResponse, StartTerminalSessionRequest, StartTerminalSessionResponse,
    StopDemoVmRequest, StopDemoVmResponse, StopTerminalSessionRequest, StopTerminalSessionResponse,
    StreamTerminalOutputRequest, TerminalControlEvent, WatchTerminalControlRequest,
};
use tddy_service::tonic_connection::connection_service_server::ConnectionService as TonicConnectionService;

/// Maps a peer uid (from SO_PEERCRED) to its OS username. Injected so the local peer-trust path is
/// host-independent and unit-testable; production wires the passwd lookup
/// (`crate::user_sessions_path::username_for_uid`).
pub type UidToUsername = Arc<dyn Fn(u32) -> Option<String> + Send + Sync>;

/// Wraps a tddy-rpc `ConnectionService` implementation so it can be served over tonic gRPC.
///
/// Construct with [`ConnectionServiceTonicAdapter::new`] and hand to
/// `tddy_service::tonic_connection::connection_service_server::ConnectionServiceServer::new`.
///
/// Every method delegates to the inner tddy-rpc handler except `MintLocalToken`, which is handled
/// here at the tonic layer: it reads the caller's peer uid from the Unix-domain-socket connect-info
/// (`UdsConnectInfo`, populated by tonic on the local socket transport), resolves it against the
/// daemon `users[]` mapping, and mints an access token with the shared `SessionTokenSigner`.
pub struct ConnectionServiceTonicAdapter<T> {
    inner: Arc<T>,
    config: Arc<DaemonConfig>,
    signer: Option<SessionTokenSigner>,
    uid_to_username: UidToUsername,
}

impl<T> ConnectionServiceTonicAdapter<T> {
    pub fn new(
        inner: Arc<T>,
        config: Arc<DaemonConfig>,
        signer: Option<SessionTokenSigner>,
        uid_to_username: UidToUsername,
    ) -> Self {
        Self {
            inner,
            config,
            signer,
            uid_to_username,
        }
    }
}

/// Convert a tddy-rpc `Status` into a tonic `Status` (tonic 0.12).
fn to_tonic_status(status: tddy_rpc::Status) -> tonic::Status {
    let code = match status.code() {
        tddy_rpc::Code::Ok => tonic::Code::Ok,
        tddy_rpc::Code::Cancelled => tonic::Code::Cancelled,
        tddy_rpc::Code::Unknown => tonic::Code::Unknown,
        tddy_rpc::Code::InvalidArgument => tonic::Code::InvalidArgument,
        tddy_rpc::Code::DeadlineExceeded => tonic::Code::DeadlineExceeded,
        tddy_rpc::Code::NotFound => tonic::Code::NotFound,
        tddy_rpc::Code::AlreadyExists => tonic::Code::AlreadyExists,
        tddy_rpc::Code::PermissionDenied => tonic::Code::PermissionDenied,
        tddy_rpc::Code::ResourceExhausted => tonic::Code::ResourceExhausted,
        tddy_rpc::Code::FailedPrecondition => tonic::Code::FailedPrecondition,
        tddy_rpc::Code::Aborted => tonic::Code::Aborted,
        tddy_rpc::Code::OutOfRange => tonic::Code::OutOfRange,
        tddy_rpc::Code::Unimplemented => tonic::Code::Unimplemented,
        tddy_rpc::Code::Internal => tonic::Code::Internal,
        tddy_rpc::Code::Unavailable => tonic::Code::Unavailable,
        tddy_rpc::Code::DataLoss => tonic::Code::DataLoss,
        tddy_rpc::Code::Unauthenticated => tonic::Code::Unauthenticated,
    };
    tonic::Status::new(code, status.message().to_string())
}

/// Convert a tonic `Status` (tonic 0.12) into a tddy-rpc `Status`.
fn to_rpc_status(status: tonic::Status) -> tddy_rpc::Status {
    let code = match status.code() {
        tonic::Code::Ok => tddy_rpc::Code::Ok,
        tonic::Code::Cancelled => tddy_rpc::Code::Cancelled,
        tonic::Code::Unknown => tddy_rpc::Code::Unknown,
        tonic::Code::InvalidArgument => tddy_rpc::Code::InvalidArgument,
        tonic::Code::DeadlineExceeded => tddy_rpc::Code::DeadlineExceeded,
        tonic::Code::NotFound => tddy_rpc::Code::NotFound,
        tonic::Code::AlreadyExists => tddy_rpc::Code::AlreadyExists,
        tonic::Code::PermissionDenied => tddy_rpc::Code::PermissionDenied,
        tonic::Code::ResourceExhausted => tddy_rpc::Code::ResourceExhausted,
        tonic::Code::FailedPrecondition => tddy_rpc::Code::FailedPrecondition,
        tonic::Code::Aborted => tddy_rpc::Code::Aborted,
        tonic::Code::OutOfRange => tddy_rpc::Code::OutOfRange,
        tonic::Code::Unimplemented => tddy_rpc::Code::Unimplemented,
        tonic::Code::Internal => tddy_rpc::Code::Internal,
        tonic::Code::Unavailable => tddy_rpc::Code::Unavailable,
        tonic::Code::DataLoss => tddy_rpc::Code::DataLoss,
        tonic::Code::Unauthenticated => tddy_rpc::Code::Unauthenticated,
    };
    tddy_rpc::Status {
        code,
        message: status.message().to_string(),
    }
}

#[tonic::async_trait]
impl<T> TonicConnectionService for ConnectionServiceTonicAdapter<T>
where
    T: RpcConnectionService,
    T::StreamSessionTerminalIoStream: 'static,
    T::StreamTerminalOutputStream: 'static,
    T::WatchTerminalControlStream: 'static,
{
    async fn list_tools(
        &self,
        request: tonic::Request<ListToolsRequest>,
    ) -> Result<tonic::Response<ListToolsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_tools(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_agents(
        &self,
        request: tonic::Request<ListAgentsRequest>,
    ) -> Result<tonic::Response<ListAgentsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_agents(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_agent_models(
        &self,
        request: tonic::Request<ListAgentModelsRequest>,
    ) -> Result<tonic::Response<ListAgentModelsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_agent_models(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_subagents(
        &self,
        request: tonic::Request<ListSubagentsRequest>,
    ) -> Result<tonic::Response<ListSubagentsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_subagents(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_sessions(
        &self,
        request: tonic::Request<ListSessionsRequest>,
    ) -> Result<tonic::Response<ListSessionsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_sessions(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_projects(
        &self,
        request: tonic::Request<ListProjectsRequest>,
    ) -> Result<tonic::Response<ListProjectsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_projects(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn create_project(
        &self,
        request: tonic::Request<CreateProjectRequest>,
    ) -> Result<tonic::Response<CreateProjectResponse>, tonic::Status> {
        let resp = RpcConnectionService::create_project(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn add_project_to_host(
        &self,
        request: tonic::Request<AddProjectToHostRequest>,
    ) -> Result<tonic::Response<AddProjectToHostResponse>, tonic::Status> {
        let resp = RpcConnectionService::add_project_to_host(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn start_session(
        &self,
        request: tonic::Request<StartSessionRequest>,
    ) -> Result<tonic::Response<StartSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::start_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn connect_session(
        &self,
        request: tonic::Request<ConnectSessionRequest>,
    ) -> Result<tonic::Response<ConnectSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::connect_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn resume_session(
        &self,
        request: tonic::Request<ResumeSessionRequest>,
    ) -> Result<tonic::Response<ResumeSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::resume_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn signal_session(
        &self,
        request: tonic::Request<SignalSessionRequest>,
    ) -> Result<tonic::Response<SignalSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::signal_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn delete_session(
        &self,
        request: tonic::Request<DeleteSessionRequest>,
    ) -> Result<tonic::Response<DeleteSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::delete_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_eligible_daemons(
        &self,
        request: tonic::Request<ListEligibleDaemonsRequest>,
    ) -> Result<tonic::Response<ListEligibleDaemonsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_eligible_daemons(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_session_workflow_files(
        &self,
        request: tonic::Request<ListSessionWorkflowFilesRequest>,
    ) -> Result<tonic::Response<ListSessionWorkflowFilesResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_session_workflow_files(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn read_session_workflow_file(
        &self,
        request: tonic::Request<ReadSessionWorkflowFileRequest>,
    ) -> Result<tonic::Response<ReadSessionWorkflowFileResponse>, tonic::Status> {
        let resp = RpcConnectionService::read_session_workflow_file(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_worktrees_for_project(
        &self,
        request: tonic::Request<ListWorktreesForProjectRequest>,
    ) -> Result<tonic::Response<ListWorktreesForProjectResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_worktrees_for_project(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn remove_worktree(
        &self,
        request: tonic::Request<RemoveWorktreeRequest>,
    ) -> Result<tonic::Response<RemoveWorktreeResponse>, tonic::Status> {
        let resp = RpcConnectionService::remove_worktree(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    /// Bidirectional streaming: convert the inbound tonic stream into a tddy-rpc `Streaming`
    /// (mapping transport errors), delegate, and box the outbound stream mapping errors back.
    type StreamSessionTerminalIOStream =
        Pin<Box<dyn Stream<Item = Result<SessionTerminalOutput, tonic::Status>> + Send>>;

    // `result_large_err`: the outbound stream's `Err` is `tonic::Status`, mandated by the
    // generated tonic trait — it cannot be boxed, so the lint's suggested fix does not apply.
    #[allow(clippy::result_large_err)]
    async fn stream_session_terminal_io(
        &self,
        request: tonic::Request<tonic::Streaming<SessionTerminalInput>>,
    ) -> Result<tonic::Response<Self::StreamSessionTerminalIOStream>, tonic::Status> {
        let inbound = request.into_inner().map(|item| item.map_err(to_rpc_status));
        let rpc_request = tddy_rpc::Request::new(tddy_rpc::Streaming::new(inbound));
        let resp = RpcConnectionService::stream_session_terminal_io(&*self.inner, rpc_request)
            .await
            .map_err(to_tonic_status)?;
        let outbound = resp.into_inner().map(|item| item.map_err(to_tonic_status));
        Ok(tonic::Response::new(Box::pin(outbound)))
    }

    /// Server streaming: browser-compatible output half.
    type StreamTerminalOutputStream =
        Pin<Box<dyn Stream<Item = Result<SessionTerminalOutput, tonic::Status>> + Send>>;

    // `result_large_err`: see `stream_session_terminal_io` — `tonic::Status` is fixed by the trait.
    #[allow(clippy::result_large_err)]
    async fn stream_terminal_output(
        &self,
        request: tonic::Request<StreamTerminalOutputRequest>,
    ) -> Result<tonic::Response<Self::StreamTerminalOutputStream>, tonic::Status> {
        let resp = RpcConnectionService::stream_terminal_output(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        let outbound = resp.into_inner().map(|item| item.map_err(to_tonic_status));
        Ok(tonic::Response::new(Box::pin(outbound)))
    }

    async fn send_terminal_input(
        &self,
        request: tonic::Request<SessionTerminalInput>,
    ) -> Result<tonic::Response<SendTerminalInputResponse>, tonic::Status> {
        let resp = RpcConnectionService::send_terminal_input(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn start_terminal_session(
        &self,
        request: tonic::Request<StartTerminalSessionRequest>,
    ) -> Result<tonic::Response<StartTerminalSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::start_terminal_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn stop_terminal_session(
        &self,
        request: tonic::Request<StopTerminalSessionRequest>,
    ) -> Result<tonic::Response<StopTerminalSessionResponse>, tonic::Status> {
        let resp = RpcConnectionService::stop_terminal_session(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_terminal_sessions(
        &self,
        request: tonic::Request<ListTerminalSessionsRequest>,
    ) -> Result<tonic::Response<ListTerminalSessionsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_terminal_sessions(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_project_branches(
        &self,
        request: tonic::Request<ListProjectBranchesRequest>,
    ) -> Result<tonic::Response<ListProjectBranchesResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_project_branches(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn execute_tool(
        &self,
        request: tonic::Request<ExecuteToolRequest>,
    ) -> Result<tonic::Response<ExecuteToolResponse>, tonic::Status> {
        let resp = RpcConnectionService::execute_tool(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_exec_tools(
        &self,
        request: tonic::Request<ListExecToolsRequest>,
    ) -> Result<tonic::Response<ListExecToolsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_exec_tools(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn list_session_tool_calls(
        &self,
        request: tonic::Request<ListSessionToolCallsRequest>,
    ) -> Result<tonic::Response<ListSessionToolCallsResponse>, tonic::Status> {
        let resp = RpcConnectionService::list_session_tool_calls(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn report_session_status(
        &self,
        request: tonic::Request<ReportSessionStatusRequest>,
    ) -> Result<tonic::Response<ReportSessionStatusResponse>, tonic::Status> {
        let resp = RpcConnectionService::report_session_status(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn start_demo_vm(
        &self,
        request: tonic::Request<StartDemoVmRequest>,
    ) -> Result<tonic::Response<StartDemoVmResponse>, tonic::Status> {
        let resp = RpcConnectionService::start_demo_vm(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn stop_demo_vm(
        &self,
        request: tonic::Request<StopDemoVmRequest>,
    ) -> Result<tonic::Response<StopDemoVmResponse>, tonic::Status> {
        let resp = RpcConnectionService::stop_demo_vm(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn get_demo_vm_status(
        &self,
        request: tonic::Request<GetDemoVmStatusRequest>,
    ) -> Result<tonic::Response<GetDemoVmStatusResponse>, tonic::Status> {
        let resp = RpcConnectionService::get_demo_vm_status(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    async fn claim_terminal_control(
        &self,
        request: tonic::Request<ClaimTerminalControlRequest>,
    ) -> Result<tonic::Response<ClaimTerminalControlResponse>, tonic::Status> {
        let resp = RpcConnectionService::claim_terminal_control(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    /// Server streaming: terminal-control ownership change events.
    type WatchTerminalControlStream =
        Pin<Box<dyn Stream<Item = Result<TerminalControlEvent, tonic::Status>> + Send>>;

    // `result_large_err`: see `stream_session_terminal_io` — `tonic::Status` is fixed by the trait.
    #[allow(clippy::result_large_err)]
    async fn watch_terminal_control(
        &self,
        request: tonic::Request<WatchTerminalControlRequest>,
    ) -> Result<tonic::Response<Self::WatchTerminalControlStream>, tonic::Status> {
        let resp = RpcConnectionService::watch_terminal_control(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        let outbound = resp.into_inner().map(|item| item.map_err(to_tonic_status));
        Ok(tonic::Response::new(Box::pin(outbound)))
    }

    async fn add_planned_pr(
        &self,
        request: tonic::Request<AddPlannedPrRequest>,
    ) -> Result<tonic::Response<AddPlannedPrResponse>, tonic::Status> {
        let resp = RpcConnectionService::add_planned_pr(
            &*self.inner,
            tddy_rpc::Request::new(request.into_inner()),
        )
        .await
        .map_err(to_tonic_status)?;
        Ok(tonic::Response::new(resp.into_inner()))
    }

    /// Peer-trust minting, handled at the tonic layer rather than delegated: the peer credential is
    /// only present on the local Unix-domain-socket transport. Deny when there is no peer-cred
    /// (any non-UDS transport), when the peer uid maps to no configured user, or when no signer is
    /// configured.
    async fn mint_local_token(
        &self,
        request: tonic::Request<MintLocalTokenRequest>,
    ) -> Result<tonic::Response<MintLocalTokenResponse>, tonic::Status> {
        let uid = request
            .extensions()
            .get::<UdsConnectInfo>()
            .and_then(|info| info.peer_cred.as_ref())
            .map(|cred| cred.uid())
            .ok_or_else(|| {
                tonic::Status::permission_denied(
                    "local token minting requires a Unix-domain-socket peer credential",
                )
            })?;

        let login = self
            .config
            .local_token_login_for_uid(uid, self.uid_to_username.as_ref())
            .ok_or_else(|| {
                tonic::Status::permission_denied(format!(
                    "peer uid {uid} is not mapped to a configured user"
                ))
            })?;

        let signer = self.signer.as_ref().ok_or_else(|| {
            tonic::Status::failed_precondition("local token minting requires a configured signer")
        })?;

        // The mapping resolves only a GitHub login; the rest of the identity is not needed to
        // authenticate subsequent RPCs (the resolver keys on `login`).
        let user = GitHubUser {
            id: 0,
            login: login.clone(),
            avatar_url: String::new(),
            name: login,
        };
        let session_token = signer.mint_access(&user);
        Ok(tonic::Response::new(MintLocalTokenResponse {
            session_token,
        }))
    }
}
