//! tddy-daemon library — shared by binary and tests.

pub mod active_elicitation;
pub mod agent_list_mapping;
pub mod auth;
mod codex_oauth_participant_metadata;
pub mod codex_oauth_relay;
pub mod config;
pub mod connection_service;
pub mod elicitation;
pub mod livekit_peer_discovery;
pub mod multi_host;
mod oauth_loopback_tunnel;
pub mod presenter_intent_client;
pub mod project_storage;
pub mod server;
pub mod session_deletion;
pub mod session_list_enrichment;
pub mod session_reader;
pub mod session_workflow_files;
pub mod spawn_worker;
pub mod spawner;
pub mod tddy_user_config;
pub mod telegram_bot;
pub mod telegram_github_link;
pub mod telegram_notifier;
pub mod telegram_session_control;
pub mod telegram_session_subscriber;
pub mod token_provider;
pub mod tunnel_management_rpc;
pub mod tunnel_streambytes_bridge;
pub mod tunnel_supervisor;
pub mod user_sessions_path;
pub mod worktrees;
