//! tddy-daemon library — shared by binary and tests.

pub mod action_service;
pub mod active_elicitation;
pub mod agent_list_mapping;
pub mod auth;
pub mod claude_cli_session;
mod codex_oauth_participant_metadata;
pub mod codex_oauth_relay;
pub mod config;
pub mod connection_service;
pub mod elicitation;
pub mod livekit_peer_discovery;
pub mod multi_host;
mod oauth_loopback_tunnel;
pub mod presenter_intent_client;
pub mod project_storage;
pub mod pty_registry;
pub mod pty_runtime;
pub mod relay_idle;
pub mod server;
pub mod session_deletion;
pub mod session_list_enrichment;
pub mod session_reader;
pub mod session_toolcall;
pub mod session_workflow_files;
pub mod spawn_worker;
pub mod spawner;
pub mod startup;
pub mod task_service;
pub mod tddy_user_config;
pub mod telegram_bot;
pub mod telegram_github_link;
pub mod telegram_multi_select_shortcuts;
pub mod telegram_notifier;
pub mod telegram_session_control;
pub mod telegram_session_subscriber;
pub mod telegram_tracked_session;
pub mod token_provider;
pub mod tool_call_log;
pub mod tool_catalog;
pub mod tool_engine;
pub mod user_sessions_path;
pub mod workspace_session;
pub mod worktrees;

pub mod sandbox_action;
pub mod sandbox_plan_builder;
pub mod sandbox_runtime;
pub mod sandbox_session;
pub mod screen_sharing_service;
pub mod screen_sharing_vault;
pub mod test_util;
pub mod vnc_service;
pub mod vnc_vault;
