//! tddy-service: Service definitions and implementations for tddy-coder.
//!
//! Exposes TddyRemote service for programmatic control via bidirectional streaming:
//! clients send UserIntent, receive PresenterView events.
//! Also provides EchoServiceImpl and TerminalServiceVirtualTui for LiveKit/gRPC terminal streaming.

pub mod acp_replay;
pub mod codex_oauth_scan;
pub mod codex_oauth_validate;
pub mod convert;
pub mod convert_acp;
pub mod echo_service;
pub mod loopback_tunnel_service;
pub mod observer_service;
pub mod presenter_intent_service;
pub mod reflection_service;
pub mod service;
pub mod service_acp;
pub mod terminal_service;
pub mod token_service;

pub use codex_oauth_scan::{
    CodexOAuthDetected, CodexOAuthPending, CodexOAuthSession, CodexOAuthSessionState,
};
pub use convert::{client_message_to_intent, event_to_server_message, snapshot_replay_messages};
pub use echo_service::{create_echo_bridge, EchoServiceImpl};
pub use loopback_tunnel_service::LoopbackTunnelServiceImpl;
pub use observer_service::PresenterObserverService;
pub use presenter_intent_service::PresenterIntentService;
pub use proto::acp::{AcpService, AcpServiceServer};
pub use proto::actions::ActionServiceServer;
pub use proto::auth::AuthServiceServer;
pub use proto::bsp::BspServiceServer;
pub use proto::connection::ConnectionServiceServer;
pub use proto::loopback_tunnel::LoopbackTunnelServiceServer;
pub use proto::reflection::ServerReflectionServer;
pub use proto::remote::TddyRemoteServer;
pub use proto::screen_sharing::ScreenSharingServiceServer;
pub use proto::tasks::TaskServiceServer;
pub use proto::terminal::TerminalServiceServer;
pub use proto::test::{EchoServiceServer, EchoServiceTonicAdapter};
pub use proto::token::{TokenServiceServer, TokenServiceTonicAdapter};
pub use proto::vm::VmServiceServer;
pub use reflection_service::{reflection_entry_from, ServerReflectionImpl};
pub use service::{session_view_adapter_surface, TddyRemoteService};
pub use service_acp::TddyAcpService;
pub use tddy_rpc::Status;
pub use terminal_service::{
    start_virtual_tui_session, TerminalServiceVirtualTui, VirtualTuiSession,
};
pub use token_service::{TokenProvider, TokenServiceImpl};

pub mod gen {
    tonic::include_proto!("tddy.v1");
}

pub mod proto {
    pub mod test {
        include!(concat!(env!("OUT_DIR"), "/test.rs"));
    }
    pub mod terminal {
        include!(concat!(env!("OUT_DIR"), "/terminal.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod token {
        include!(concat!(env!("OUT_DIR"), "/token.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod auth {
        include!(concat!(env!("OUT_DIR"), "/auth.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod connection {
        include!(concat!(env!("OUT_DIR"), "/connection.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod bsp {
        include!(concat!(env!("OUT_DIR"), "/bsp.rs"));
    }
    pub mod loopback_tunnel {
        include!(concat!(env!("OUT_DIR"), "/loopback_tunnel.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod vm {
        include!(concat!(env!("OUT_DIR"), "/vm.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod tasks {
        include!(concat!(env!("OUT_DIR"), "/tasks.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod actions {
        include!(concat!(env!("OUT_DIR"), "/actions.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod vnc {
        include!(concat!(env!("OUT_DIR"), "/vnc.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod vnc_input {
        include!(concat!(env!("OUT_DIR"), "/vnc_input.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod screen_sharing {
        include!(concat!(env!("OUT_DIR"), "/screen_sharing.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod screen_sharing_input {
        include!(concat!(env!("OUT_DIR"), "/screen_sharing_input.rs"));
    }
    #[allow(unused_imports, unused_variables)]
    pub mod sandbox {
        include!(concat!(env!("OUT_DIR"), "/sandbox.rs"));
    }
    pub mod reflection {
        include!(concat!(env!("OUT_DIR"), "/grpc.reflection.v1.rs"));
    }
    /// `AcpService`: the protobuf mirror of ACP as an `RpcService` (stdio and LiveKit/`tddy_rpc`
    /// transports). Self-contained proto generated by the `tddy_codegen` RpcService pass.
    #[allow(dead_code, unused_imports, unused_variables)]
    pub mod acp {
        include!(concat!(env!("OUT_DIR"), "/tddy.acp.v1.rs"));
    }
    /// `TddyRemote` as an `RpcService` (stdio and LiveKit/`MultiRpcService` transports), reusing
    /// the tonic-generated message types from `crate::gen` via `extern_path`. Most of
    /// remote.proto's ~30 nested message types aren't referenced directly by the service methods
    /// (only transitively, through the already-extern'd `ClientMessage`/`ServerMessage`), so
    /// prost regenerates them here too as unused duplicates — harmless, but silenced like the
    /// other proto modules below.
    #[allow(dead_code, unused_imports, unused_variables)]
    pub mod remote {
        include!(concat!(env!("OUT_DIR"), "/rpc_remote/tddy.v1.rs"));
    }
}

/// Convert a [`serde_json::Value`] into the protobuf [`prost_types::Value`] wire form for a
/// `google.protobuf.Value` field.
///
/// [`serde_json::Value::Null`] at the top level maps to `None` — i.e. the proto field is left
/// unset. This gives the agent-activity "running row leaves `result` unset" / "empty input is
/// unset" semantics uniformly. Every other JSON shape maps faithfully: object →
/// `StructValue`, array → `ListValue`, string → `StringValue`, number → `NumberValue`, bool →
/// `BoolValue`. A `null` nested *inside* an object/array is preserved as a `NullValue` kind.
pub fn json_to_proto_value(value: &serde_json::Value) -> Option<prost_types::Value> {
    if value.is_null() {
        return None;
    }
    Some(json_to_prost_value(value))
}

fn json_to_prost_value(value: &serde_json::Value) -> prost_types::Value {
    use prost_types::value::Kind;
    let kind = match value {
        serde_json::Value::Null => Kind::NullValue(0),
        serde_json::Value::Bool(b) => Kind::BoolValue(*b),
        serde_json::Value::Number(n) => Kind::NumberValue(n.as_f64().unwrap_or(0.0)),
        serde_json::Value::String(s) => Kind::StringValue(s.clone()),
        serde_json::Value::Array(arr) => Kind::ListValue(prost_types::ListValue {
            values: arr.iter().map(json_to_prost_value).collect(),
        }),
        serde_json::Value::Object(map) => Kind::StructValue(prost_types::Struct {
            fields: map
                .iter()
                .map(|(k, v)| (k.clone(), json_to_prost_value(v)))
                .collect(),
        }),
    };
    prost_types::Value { kind: Some(kind) }
}

/// Map a durable [`tddy_core::agent_activity::AgentActivityRecord`] onto its protobuf wire form
/// [`proto::connection::AgentActivityRecord`].
///
/// The structured `input` / `result` JSON values are carried as `google.protobuf.Value` via
/// [`json_to_proto_value`], so a top-level `Null` leaves the corresponding proto field unset.
/// All scalar fields are copied through verbatim.
pub fn agent_activity_to_proto(
    record: tddy_core::agent_activity::AgentActivityRecord,
) -> proto::connection::AgentActivityRecord {
    proto::connection::AgentActivityRecord {
        call_id: record.call_id,
        tool_name: record.tool_name,
        input: json_to_proto_value(&record.input),
        status: record.status,
        result: json_to_proto_value(&record.result),
        error_message: record.error_message,
        started_unix_ms: record.started_unix_ms,
        completed_unix_ms: record.completed_unix_ms,
        source: record.source,
    }
}

/// Combined `FileDescriptorSet` (serialized) for all service protos, used by the
/// gRPC `ServerReflection` service to serve descriptors at runtime.
pub static SERVICE_DESCRIPTOR_BYTES: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/service_descriptors.bin"));

/// Tonic-generated gRPC server/client for terminal.proto.
/// Uses the same message types as `proto::terminal` (via extern_path).
pub mod tonic_terminal {
    #![allow(unused_imports, clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/tonic_terminal/terminal.rs"));
}

/// Tonic-generated gRPC server/client for sandbox.proto.
pub mod tonic_sandbox {
    #![allow(unused_imports, clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/tonic_sandbox/sandbox.rs"));
}

/// Tonic-generated gRPC server/client for connection.proto.
/// Uses the same message types as `proto::connection` (via extern_path), kept in a separate
/// module from the tddy-rpc `ConnectionServiceServer` (re-exported above) so the two service
/// codegen flavors do not collide.
pub mod tonic_connection {
    #![allow(unused_imports, clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/tonic_connection/connection.rs"));
}

#[cfg(test)]
mod json_to_proto_value_tests {
    use super::json_to_proto_value;
    use prost_types::value::Kind;

    /// Unwrap the produced `Some(Value)` down to its `Kind`, failing loudly if the field was
    /// left unset — keeps each test asserting one exact kind.
    fn kind_of(value: &serde_json::Value) -> Kind {
        json_to_proto_value(value)
            .expect("expected the proto field to be set")
            .kind
            .expect("proto Value must carry a kind")
    }

    /// A top-level JSON `null` leaves the `google.protobuf.Value` field unset (`None`), giving
    /// agent-activity its "running row has no result / empty input is absent" semantics.
    #[test]
    fn maps_top_level_null_to_an_unset_field() {
        // Given
        let value = serde_json::Value::Null;

        // When
        let proto = json_to_proto_value(&value);

        // Then
        assert_eq!(
            proto, None,
            "top-level null must leave the proto field unset"
        );
    }

    /// A bare JSON string maps to a `StringValue`, so non-object tool text round-trips faithfully.
    #[test]
    fn maps_a_bare_string_to_a_string_value() {
        // Given
        let value = serde_json::json!("hello");

        // When
        let kind = kind_of(&value);

        // Then
        assert_eq!(kind, Kind::StringValue("hello".to_string()));
    }

    /// A JSON object maps to a `StructValue` whose fields carry the object's entries.
    #[test]
    fn maps_an_object_to_a_struct_value() {
        // Given
        let value = serde_json::json!({ "command": "x" });

        // When
        let kind = kind_of(&value);

        // Then
        let Kind::StructValue(s) = kind else {
            panic!("expected a StructValue, got {kind:?}");
        };
        assert_eq!(s.fields.len(), 1, "struct must carry exactly one field");
        assert_eq!(
            s.fields.get("command").and_then(|v| v.kind.clone()),
            Some(Kind::StringValue("x".to_string())),
            "the 'command' field must be a StringValue('x')"
        );
    }

    /// A JSON array maps to a `ListValue` preserving element order and kinds.
    #[test]
    fn maps_an_array_to_a_list_value() {
        // Given
        let value = serde_json::json!(["a", "b"]);

        // When
        let kind = kind_of(&value);

        // Then
        let Kind::ListValue(list) = kind else {
            panic!("expected a ListValue, got {kind:?}");
        };
        let kinds: Vec<Option<Kind>> = list.values.into_iter().map(|v| v.kind).collect();
        assert_eq!(
            kinds,
            vec![
                Some(Kind::StringValue("a".to_string())),
                Some(Kind::StringValue("b".to_string())),
            ]
        );
    }

    /// A JSON boolean maps to a `BoolValue`.
    #[test]
    fn maps_a_bool_to_a_bool_value() {
        // Given
        let value = serde_json::json!(true);

        // When
        let kind = kind_of(&value);

        // Then
        assert_eq!(kind, Kind::BoolValue(true));
    }

    /// A JSON number maps to a `NumberValue` (IEEE-754 double).
    #[test]
    fn maps_a_number_to_a_number_value() {
        // Given
        let value = serde_json::json!(42);

        // When
        let kind = kind_of(&value);

        // Then
        assert_eq!(kind, Kind::NumberValue(42.0));
    }

    /// A `null` nested inside an object is preserved as a `NullValue` kind — only a *top-level*
    /// null unsets the field. This guards the doc-comment claim on [`json_to_proto_value`].
    #[test]
    fn preserves_a_null_nested_inside_an_object_as_null_value() {
        // Given
        let value = serde_json::json!({ "a": null });

        // When
        let kind = kind_of(&value);

        // Then
        let Kind::StructValue(s) = kind else {
            panic!("expected a StructValue, got {kind:?}");
        };
        assert_eq!(
            s.fields.get("a").and_then(|v| v.kind.clone()),
            Some(Kind::NullValue(0)),
            "a nested null must be preserved as a NullValue kind, not dropped"
        );
    }
}

#[cfg(test)]
mod integration_tests;

#[cfg(test)]
mod test_util {
    /// Spawn a gRPC server on an ephemeral port. Returns the endpoint URL
    /// and the server's JoinHandle. Yields once to let the server start.
    pub async fn spawn_server(
        router: tonic::transport::server::Router,
    ) -> (
        String,
        tokio::task::JoinHandle<Result<(), tonic::transport::Error>>,
    ) {
        let listener = tokio::net::TcpListener::bind("[::1]:0").await.unwrap();
        let port = listener.local_addr().unwrap().port();
        let endpoint = format!("http://[::1]:{}", port);

        let handle = tokio::spawn(async move {
            router
                .serve_with_incoming(tokio_stream::wrappers::TcpListenerStream::new(listener))
                .await
        });

        tokio::task::yield_now().await;
        (endpoint, handle)
    }

    /// Spawn a gRPC server on an ephemeral port and return a connected client.
    pub async fn spawn_server_and_connect(
        router: tonic::transport::server::Router,
    ) -> crate::gen::tddy_remote_client::TddyRemoteClient<tonic::transport::Channel> {
        let (endpoint, _handle) = spawn_server(router).await;
        crate::gen::tddy_remote_client::TddyRemoteClient::connect(endpoint)
            .await
            .unwrap()
    }
}
