//! Generate `goal_registry.rs` from `tddy-workflow-recipes/goals.json` (single source of truth).
//! Ensure `tddy-workflow-recipes` builds first so `generated/` exists before `include_dir!`.

use std::env;
use std::fs;
use std::io;
use std::path::Path;

fn main() -> io::Result<()> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let goals_path = manifest_dir.join("../tddy-workflow-recipes/goals.json");
    let out_dir = env::var("OUT_DIR").map_err(io::Error::other)?;

    println!("cargo:rerun-if-changed={}", goals_path.display());
    println!("cargo:rerun-if-changed=../tddy-workflow-recipes/generated");
    println!("cargo:rerun-if-changed=../tddy-workflow-recipes/build.rs");
    println!("cargo:rerun-if-changed=../tddy-workflow-recipes/goals.json");
    println!("cargo:rerun-if-changed=../tddy-workflow-recipes/proto");

    let raw = fs::read_to_string(&goals_path)?;
    let root: serde_json::Value = serde_json::from_str(&raw)
        .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, format!("goals.json: {}", e)))?;
    let goals_arr = root["goals"].as_array().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            "goals.json: missing goals array",
        )
    })?;

    const RECIPE_NAME: &str = "tdd";

    let mut rs = String::from(
        "/// Generated by tddy-tools/build.rs from goals.json — do not edit.\npub const GOAL_SCHEMA_FILES: &[(&str, &str)] = &[\n",
    );
    for g in goals_arr {
        let name = g["name"]
            .as_str()
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "goal.name"))?;
        let schema = g["schema"]
            .as_str()
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "goal.schema"))?;
        rs.push_str("    (\"");
        rs.push_str(name);
        rs.push_str("\", \"");
        rs.push_str(RECIPE_NAME);
        rs.push('/');
        rs.push_str(schema);
        rs.push_str("\"),\n");
    }
    rs.push_str("];\n");

    fs::write(Path::new(&out_dir).join("goal_registry.rs"), rs)?;
    Ok(())
}
