//! Validate `generated/{recipe}/` schemas and protos referenced in `goals.json`,
//! write `schema-manifest.json`, and emit `generated/proto_basenames.rs`
//! (single source of truth for CLI goal name ↔ schema file ↔ proto file).

use std::fs;
use std::io;
use std::path::PathBuf;

const RECIPE_NAME: &str = "tdd";

fn main() -> io::Result<()> {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let goals_path = manifest_dir.join("goals.json");
    let generated = manifest_dir.join("generated");
    let recipe_dir = generated.join(RECIPE_NAME);

    println!("cargo:rerun-if-changed={}", goals_path.display());
    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir.join("build.rs").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir.join("proto").display()
    );
    println!("cargo:rerun-if-changed={}", recipe_dir.display());

    let goals_raw = fs::read_to_string(&goals_path)?;
    let root: serde_json::Value = serde_json::from_str(&goals_raw)
        .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, format!("goals.json: {}", e)))?;
    let goals_arr = root["goals"].as_array().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            "goals.json: missing \"goals\" array",
        )
    })?;

    for g in goals_arr {
        let schema = g["schema"]
            .as_str()
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "goal entry: schema"))?;
        let proto = g["proto"]
            .as_str()
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "goal entry: proto"))?;
        let schema_path = recipe_dir.join(schema);
        if !schema_path.is_file() {
            return Err(io::Error::new(
                io::ErrorKind::NotFound,
                format!("missing schema {}", schema_path.display()),
            ));
        }
        let proto_path = manifest_dir.join("proto").join(proto);
        if !proto_path.is_file() {
            return Err(io::Error::new(
                io::ErrorKind::NotFound,
                format!("missing proto {}", proto_path.display()),
            ));
        }
    }

    fs::create_dir_all(&generated)?;

    let manifest_goals: Vec<serde_json::Value> = goals_arr
        .iter()
        .map(|g| {
            serde_json::json!({
                "name": g["name"],
                "schema": g["schema"],
                "proto": g["proto"],
            })
        })
        .collect();

    let manifest = serde_json::json!({
        "version": 1,
        "goals": manifest_goals
    });

    let manifest_path = generated.join("schema-manifest.json");
    fs::write(
        &manifest_path,
        serde_json::to_string_pretty(&manifest).unwrap(),
    )?;

    let mut proto_rs = String::from(
        "/// Generated by build.rs from goals.json — do not edit.\npub const EXPECTED_PROTO_BASENAMES: &[&str] = &[\n",
    );
    for g in goals_arr {
        let proto = g["proto"].as_str().expect("proto checked");
        proto_rs.push_str("    \"");
        proto_rs.push_str(proto);
        proto_rs.push_str("\",\n");
    }
    proto_rs.push_str("];\n");
    fs::write(generated.join("proto_basenames.rs"), proto_rs)?;

    println!(
        "tddy-workflow-recipes: wrote {}, proto_basenames.rs; validated schemas in {}",
        manifest_path.display(),
        recipe_dir.display()
    );

    Ok(())
}
